data_processing:
  atom_config:
    feature_attributes:
      atom_symbol:
        include_other: true
        top_n_atoms: 42
    features:
      aromatic: true
      atom_symbol: true
      default_valence: true
      formal_charge: true
      hybridization: true
      hydrogen_count: true
      ring_size: true
      total_valence: true
  bond_config:
    features:
      bond_type: true
      conjugated: true
      in_ring: true
      stereochemistry: false
  global_features:
    features:
      collision_energy: true
      adduct: true
      instrument_type: true
      precursor_mz: true
model:
  input_layer:
    type: 'TRANSFORMER_CONV'
    params:
      node_features: 84
      edge_features: 7
      embedding_size_reduced: 128
  global_input_layer:
    type: 'GlobalInputLayer'
    params:
      input_size: 17          # Total number of global features (10 + 3 + 3 + 1)
      output_size: 50
      num_skipblocks: 1
      hidden_size: 100
  body_layer:
    type: 'SKIPBLOCK_BODY'
    params:
      embedding_size_gnn: 128
      embedding_size: 256
      num_skipblocks: 7
      pooling_fn: 'mean'
      use_global_features: true
      global_embedding_size: 50
  head_layer:
    type: 'BidirectionalHeadLayer'
    params:
      input_size: 256
      output_size: 1024
training:
  trainer:
    type: 'Trainer'  # Or 'TripletTrainer' if using triplet loss
    params: {}
  num_epochs: 10
  validate_every: 2
  save_every: 2
  save_best_only: true
  device: 'cpu'
  log_dir: '../../data/logs/mol2dreams'
  loss_function:
    type: 'CosineEmbeddingLoss'
    params: {}
  optimizer:
    type: 'Adam'
    params:
      lr: 0.001
  train_loader:
    path: '../../data/data/precomputed_all_features_batches_small.pt'
    dataset_type: 'SimpleDataset'
    batch_size: 32
    num_workers: 0
    shuffle: true
  val_loader:
    path: '../../data/data/precomputed_all_features_batches_small.pt'
    dataset_type: 'SimpleDataset'
    batch_size: 32
    num_workers: 0
    shuffle: false
  test_loader:
    path: '../../data/data/precomputed_all_features_batches_small.pt'
    dataset_type: 'SimpleDataset'
    batch_size: 32
    num_workers: 0
    shuffle: false