data_processing:
  atom_config:
    feature_attributes:
      atom_symbol:
        include_other: true
        top_n_atoms: 42
    features:
      aromatic: true
      atom_symbol: true
      default_valence: true
      formal_charge: true
      hybridization: true
      hydrogen_count: true
      ring_size: true
      total_valence: true
  bond_config:
    features:
      bond_type: true
      conjugated: true
      in_ring: true
      stereochemistry: false
model:
  body_layer:
    params:
      embedding_size: 256
      embedding_size_gnn: 128
      num_skipblocks: 7
      pooling_fn: mean
    type: SKIPBLOCK_BODY
  head_layer:
    params:
      input_size: 256
      output_size: 1024
    type: BidirectionalHeadLayer
  input_layer:
    params:
      embedding_size_reduced: 128
      node_features: 84
    type: CONV_GNN
training:
  device: cpu
  log_dir: /Users/macbook/CODE/mol2DreaMS/mol2dreams/logs
  loss_function:
    params: {}
    type: MSELoss
  num_epochs: 50
  optimizer:
    params:
      lr: 0.001
    type: Adam
  save_best_only: true
  save_every: 5
  test_loader:
    path: /Users/macbook/CODE/mol2DreaMS/data/data/precomputed_batches_small.pt
  train_loader:
    path: /Users/macbook/CODE/mol2DreaMS/data/data/precomputed_batches_small.pt
  val_loader:
    path: /Users/macbook/CODE/mol2DreaMS/data/data/precomputed_batches_small.pt
  validate_every: 5
